### ISSUE TITLE
PHP Fatal error: Cannot redeclare Composer\Autoload\includeFile()

### ISSUE THREAD

**Issue by joselbr2099** [Merujan99/laravel-video-embed#2]
please help me, I had this problem after installing this extension

https://stackoverflow.com/questions/50791200/php-fatal-error-cannot-redeclare-composer-autoload-includefile?noredirect=1#comment88588517_50791200

**Comment by Merujan99** [comment]
Can you please give me details what version of Laravel do you use, or can I have read access to your repository?

**Comment by Merujan99** [comment]
Also https://stackoverflow.com/questions/36064067/composer-error-installing-laravel-cors
Here it says that the problem can be, if you require package not in root directory, You cannot have any vendor folder in the config folder, so you wrote "composer install .." in config folder. 
So delete vendor folder from config. and it'll work. 
I'm closing issue, and it's not related to this package.
