### ISSUE TITLE
Class 'App\Http\Controllers\LaravelVideoEmbed' not found

### ISSUE THREAD

**Issue by iSarahSajjad** [Merujan99/laravel-video-embed#3]
I used it your as documented but getting this error "Class 'App\Http\Controllers\LaravelVideoEmbed' not found" on laravel 5.7

**Comment by Merujan99** [comment]
I need to update library for Laravel 5.7

**Comment by mdsami** [comment]
After completing the step above, use the following command to publish configuration settings:

php artisan vendor:publish --provider="Merujan99\LaravelVideoEmbed\Providers\LaravelVideoEmbedServiceProvider"

then just add

use LaravelVideoEmbed;

this your controller   . this will fixed your issues @iSarahSajjad
