### ISSUE TITLE
add publish configuration in readme file 

### ISSUE THREAD

**Issue by mdsami** [Merujan99/laravel-video-embed#4]
After completing the step above, use the following command to publish configuration settings:

php artisan vendor:publish --provider="Merujan99\LaravelVideoEmbed\Providers\LaravelVideoEmbedServiceProvider"

then just add 

use LaravelVideoEmbed;

this your controller

**Comment by Merujan99** [comment]
Can you please create pull request, and I'll merge.

**Comment by mdsami** [comment]
@Merujan99  i  create a pull request, merge it.
Thanks
