### ISSUE TITLE
Attributes are not parsed correctly. 

### ISSUE THREAD

**Issue by KangarooMusiQue** [Merujan99/laravel-video-embed#7]
If i add attributes to the command they dont appear in the html source code. 
I checked the file "LaravelVideoEmbed.php" in the Services-Directory and it seems that  the if(is_array() is set wrong: 

i tried to correct this from $params to $attributes but it doesnt change anything. Maybe you can fix this?
```
      if(is_array($attributes))
      {
        $MediaObject->setAttribute($attributes);
      }
```

**Comment by Merujan99** [comment]
You're right, it need to be $attributes and it need to be work, I'll update repo, try to clear and pull it again and try
